name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the ccl-docs repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the Docusaurus project
      - name: Build the project
        run: npm run build

      # Step 5: Clone the public-docs repository
      - name: Clone the public-docs repo
        run: |
          git clone https://github.com/chitchatlabs/public-docs.git
          rm -rf public-docs/*  # Clean up the public-docs folder

      # Step 6: Copy the build output to public-docs
      - name: Copy build output
        run: cp -rvf build/* public-docs/

      # Step 7: Commit and push the changes to public-docs
      - name: Commit and push changes
        run: |
          cd public-docs
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -A
          git commit -m "Deploy Docusaurus to GitHub Pages" || echo "No changes to commit"
          git push https://${{ secrets.GH_PAGES_PAT }}@github.com/chitchatlabs/public-docs.git main

      # Step 8: Send Slack notification
      - name: Send Slack notification
        if: always()
        run: |
          curl -X POST -H 'Content-type: application/json' --data "{
            \"attachments\": [
              {
                \"fallback\": \"Documentation UI Deployment Status\",
                \"color\": \"#36a64f\",
                \"pretext\": \"*Documentation UI Deployment Notification* 🚀\",
                \"title\": \"Deployment to GitHub Pages\",
                \"text\": \"Documentation UI build pushed to public repo.\",
                \"fields\": [
                  {
                    \"title\": \"Status\",
                    \"value\": \"${{ job.status }}\",
                    \"short\": true
                  },
                  {
                    \"title\": \"Branch\",
                    \"value\": \"${{ github.ref_name }}\",
                    \"short\": true
                  },
                  {
                    \"title\": \"Public Repository\",
                    \"value\": \"<https://github.com/chitchatlabs/public-docs|public-docs>\"
                  }
                ],
                \"footer\": \"GitHub Actions\",
                \"footer_icon\": \"https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png\",
                \"ts\": $(date +%s)
              }
            ]
          }" ${{ secrets.SLACK_WEBHOOK_URL }}
